Added initial home page image with text
matt-cha/matthew-cha-photography pull request #1
Opened 2024-08-12 23:58 UTC by matt-cha

2024-08-13 01:31 UTC, joseph-w-valdez requested changes

2024-08-13 01:31 UTC, joseph-w-valdez commented on public/JJ-1396.jpg
should format the name of this file

2024-08-13 01:31 UTC, joseph-w-valdez commented on src/app/page.tsx
> +    //   </div>
don't comment out unused code

2024-08-13 01:31 UTC, joseph-w-valdez commented on src/app/page.tsx
> +    //   </div>
same as above

2024-08-13 01:31 UTC, joseph-w-valdez commented on src/app/page.tsx
> +    //     </a>
same as above

2024-08-13 01:31 UTC, joseph-w-valdez commented on src/app/page.tsx
> +    //     </a>
same as above

2024-08-13 01:31 UTC, joseph-w-valdez commented on src/app/page.tsx
> +    //     </a>
same as above

2024-08-13 01:31 UTC, joseph-w-valdez commented on src/app/page.tsx
> +    // </main>
same as above

2024-08-13 01:31 UTC, joseph-w-valdez commented on src/app/page.tsx
> +        src="/JJ-1396.jpg"
import this image like `import banner from '/rel-path.jpg` and use `banner` as the `src` here

2024-08-13 02:07 UTC, joseph-w-valdez requested changes

2024-08-13 02:07 UTC, joseph-w-valdez commented on public/main-image-1.jpg
should omit the `-1`. if you're gonna use this on the main page, `banner.jpg` and `main.jpg` are probably better. no need to include `image` in the file name as it's already a `.jpg` file

2024-08-13 02:07 UTC, joseph-w-valdez commented on src/app/contact/page.tsx
why does this file exist if this PR is just for the home page

2024-08-13 19:41 UTC, matt-cha commented on src/app/page.tsx
> +        src={main.src}
It was giving me a TS Error so I looked into it and it's accessing the StaticImageData type vs what it actually wants which is a string. This prevents the TS error on my end!

2024-08-13 19:42 UTC, matt-cha commented on src/app/contact/page.tsx
> +"use client";
Removed the file, will put this into a separate branch

2024-08-13 19:47 UTC, matt-cha commented on src/app/page.tsx
> +    </div>
Root div to main, got it. Is this more a semantic, organizational code practice?

2024-08-14 00:09 UTC, joseph-w-valdez commented on public/main.jpg
is this meant to be 20MB? quite a large file for the splash page

2024-08-14 00:10 UTC, joseph-w-valdez commented on src/app/page.tsx
> +    </div>
important for both reasons yeah. not necessarily root div, but the -main- content on the page. you can have other sibling divs here like aside elements, etc.

2024-08-14 00:12 UTC, joseph-w-valdez approved these changes

2024-08-14 05:44 UTC, merged